// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SHB.Infrastructure.Repositories;

#nullable disable

namespace SHB.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231112142847_init-project")]
    partial class initproject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SHB.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PracticalHours")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TheoreticalHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseCode = "C001",
                            Name = "Introduction to Programming",
                            PracticalHours = 30,
                            ProgramId = 1,
                            Semester = 1,
                            TheoreticalHours = 60
                        },
                        new
                        {
                            Id = 2,
                            CourseCode = "C002",
                            Name = "Data Structures and Algorithms",
                            PracticalHours = 35,
                            ProgramId = 1,
                            Semester = 1,
                            TheoreticalHours = 55
                        },
                        new
                        {
                            Id = 3,
                            CourseCode = "C003",
                            Name = "Database Management",
                            PracticalHours = 25,
                            ProgramId = 2,
                            Semester = 1,
                            TheoreticalHours = 45
                        },
                        new
                        {
                            Id = 4,
                            CourseCode = "C004",
                            Name = "Web Development",
                            PracticalHours = 40,
                            ProgramId = 2,
                            Semester = 1,
                            TheoreticalHours = 50
                        },
                        new
                        {
                            Id = 5,
                            CourseCode = "C005",
                            Name = "Operating Systems",
                            PracticalHours = 30,
                            ProgramId = 3,
                            Semester = 1,
                            TheoreticalHours = 60
                        },
                        new
                        {
                            Id = 6,
                            CourseCode = "C006",
                            Name = "Computer Networks",
                            PracticalHours = 35,
                            ProgramId = 3,
                            Semester = 1,
                            TheoreticalHours = 55
                        },
                        new
                        {
                            Id = 7,
                            CourseCode = "C007",
                            Name = "Software Engineering",
                            PracticalHours = 30,
                            ProgramId = 4,
                            Semester = 1,
                            TheoreticalHours = 60
                        },
                        new
                        {
                            Id = 8,
                            CourseCode = "C008",
                            Name = "Machine Learning",
                            PracticalHours = 40,
                            ProgramId = 4,
                            Semester = 1,
                            TheoreticalHours = 50
                        },
                        new
                        {
                            Id = 9,
                            CourseCode = "C009",
                            Name = "Mobile App Development",
                            PracticalHours = 35,
                            ProgramId = 5,
                            Semester = 1,
                            TheoreticalHours = 55
                        },
                        new
                        {
                            Id = 10,
                            CourseCode = "C010",
                            Name = "Artificial Intelligence",
                            PracticalHours = 40,
                            ProgramId = 5,
                            Semester = 1,
                            TheoreticalHours = 50
                        });
                });

            modelBuilder.Entity("SHB.Domain.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6283),
                            CreatedBy = "Admin",
                            Description = "Description for Computer Science faculty",
                            Name = "Faculty of Computer Science",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6283),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6285),
                            CreatedBy = "Admin",
                            Description = "Description for Electrical Engineering faculty",
                            Name = "Faculty of Electrical Engineering",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6286),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6287),
                            CreatedBy = "Admin",
                            Description = "Description for Mechanical Engineering faculty",
                            Name = "Faculty of Mechanical Engineering",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6287),
                            UpdatedBy = "Admin"
                        });
                });

            modelBuilder.Entity("SHB.Domain.FieldOfStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("FieldOfStudy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6299),
                            CreatedBy = "Admin",
                            FacultyId = 1,
                            Name = "Computer Science",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6300),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6302),
                            CreatedBy = "Admin",
                            FacultyId = 2,
                            Name = "Electrical Engineering",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6302),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6303),
                            CreatedBy = "Admin",
                            FacultyId = 3,
                            Name = "Mechanical Engineering",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6304),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6305),
                            CreatedBy = "Admin",
                            FacultyId = 1,
                            Name = "Physics",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6305),
                            UpdatedBy = "Admin"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6306),
                            CreatedBy = "Admin",
                            FacultyId = 2,
                            Name = "Mathematics",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6307),
                            UpdatedBy = "Admin"
                        });
                });

            modelBuilder.Entity("SHB.Domain.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FieldOfStudyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldOfStudyId");

                    b.ToTable("Program");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6319),
                            CreatedBy = "Admin",
                            FieldOfStudyId = 1,
                            Name = "Computer Science Program",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6320),
                            UpdatedBy = "Admin",
                            Year = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6322),
                            CreatedBy = "Admin",
                            FieldOfStudyId = 2,
                            Name = "Electrical Engineering Program",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6322),
                            UpdatedBy = "Admin",
                            Year = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6323),
                            CreatedBy = "Admin",
                            FieldOfStudyId = 3,
                            Name = "Mechanical Engineering Program",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6324),
                            UpdatedBy = "Admin",
                            Year = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6325),
                            CreatedBy = "Admin",
                            FieldOfStudyId = 4,
                            Name = "Physics Program",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6325),
                            UpdatedBy = "Admin",
                            Year = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6327),
                            CreatedBy = "Admin",
                            FieldOfStudyId = 5,
                            Name = "Mathematics Program",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6327),
                            UpdatedBy = "Admin",
                            Year = 3
                        });
                });

            modelBuilder.Entity("SHB.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("FieldOfStudyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FieldOfStudyId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            BirthDay = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anytown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6419),
                            CreatedBy = "Admin",
                            Email = "john.doe@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 1,
                            FirstName = "John",
                            FullName = "John Doe Smith",
                            LastName = "Smith",
                            MiddleName = "Doe",
                            Password = "12345",
                            Phone = "123-456-7890",
                            PostalCode = "12345",
                            ProgramId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6419),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm Street",
                            BirthDay = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6423),
                            CreatedBy = "Admin",
                            Email = "alice.eve@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 2,
                            FirstName = "Alice",
                            FullName = "Alice Eve Johnson",
                            LastName = "Johnson",
                            MiddleName = "Eve",
                            Password = "12345",
                            Phone = "456-789-0123",
                            PostalCode = "54321",
                            ProgramId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6424),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak Street",
                            BirthDay = new DateTime(1988, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anothercity",
                            Country = "UK",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6427),
                            CreatedBy = "Admin",
                            Email = "michael.james@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 3,
                            FirstName = "Michael",
                            FullName = "Michael James Brown",
                            LastName = "Brown",
                            MiddleName = "James",
                            Password = "12345",
                            Phone = "789-012-3456",
                            PostalCode = "98765",
                            ProgramId = 3,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6427),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Oak Lane",
                            BirthDay = new DateTime(1991, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6430),
                            CreatedBy = "Admin",
                            Email = "sarah.jane@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 4,
                            FirstName = "Sarah",
                            FullName = "Sarah Jane Wilson",
                            LastName = "Wilson",
                            MiddleName = "Jane",
                            Password = "12345",
                            Phone = "555-123-4567",
                            PostalCode = "54321",
                            ProgramId = 4,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6430),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "567 Elm Road",
                            BirthDay = new DateTime(1987, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anytown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6432),
                            CreatedBy = "Admin",
                            Email = "robert.david@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 5,
                            FirstName = "Robert",
                            FullName = "Robert David Jones",
                            LastName = "Jones",
                            MiddleName = "David",
                            Password = "12345",
                            Phone = "567-234-5678",
                            PostalCode = "12345",
                            ProgramId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6432),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "222 Maple Street",
                            BirthDay = new DateTime(1992, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6435),
                            CreatedBy = "Admin",
                            Email = "emily.grace@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 1,
                            FirstName = "Emily",
                            FullName = "Emily Grace Martinez",
                            LastName = "Martinez",
                            MiddleName = "Grace",
                            Password = "12345",
                            Phone = "222-345-6789",
                            PostalCode = "98765",
                            ProgramId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6436),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Address = "444 Cedar Lane",
                            BirthDay = new DateTime(1986, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6438),
                            CreatedBy = "Admin",
                            Email = "william.joseph@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 2,
                            FirstName = "William",
                            FullName = "William Joseph Lee",
                            LastName = "Lee",
                            MiddleName = "Joseph",
                            Password = "12345",
                            Phone = "444-456-7890",
                            PostalCode = "12345",
                            ProgramId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6438),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "777 Pine Road",
                            BirthDay = new DateTime(1993, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6440),
                            CreatedBy = "Admin",
                            Email = "olivia.sophia@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 3,
                            FirstName = "Olivia",
                            FullName = "Olivia Sophia Garcia",
                            LastName = "Garcia",
                            MiddleName = "Sophia",
                            Password = "12345",
                            Phone = "777-567-1234",
                            PostalCode = "54321",
                            ProgramId = 3,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6440),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "555 Birch Lane",
                            BirthDay = new DateTime(1989, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6442),
                            CreatedBy = "Admin",
                            Email = "james.andrew@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 4,
                            FirstName = "James",
                            FullName = "James Andrew Davis",
                            LastName = "Davis",
                            MiddleName = "Andrew",
                            Password = "12345",
                            Phone = "555-123-6789",
                            PostalCode = "98765",
                            ProgramId = 4,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6443),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            Address = "333 Cedar Road",
                            BirthDay = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6445),
                            CreatedBy = "Admin",
                            Email = "sophia.grace@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 5,
                            FirstName = "Sophia",
                            FullName = "Sophia Grace Hernandez",
                            LastName = "Hernandez",
                            MiddleName = "Grace",
                            Password = "12345",
                            Phone = "333-234-5678",
                            PostalCode = "12345",
                            ProgramId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6446),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            Address = "777 Pine Lane",
                            BirthDay = new DateTime(1995, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6448),
                            CreatedBy = "Admin",
                            Email = "logan.david@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 1,
                            FirstName = "Logan",
                            FullName = "Logan David Lopez",
                            LastName = "Lopez",
                            MiddleName = "David",
                            Password = "12345",
                            Phone = "777-567-6789",
                            PostalCode = "54321",
                            ProgramId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6448),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Address = "444 Maple Lane",
                            BirthDay = new DateTime(1996, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anothercity",
                            Country = "UK",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6450),
                            CreatedBy = "Admin",
                            Email = "ava.emily@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 2,
                            FirstName = "Ava",
                            FullName = "Ava Emily Thompson",
                            LastName = "Thompson",
                            MiddleName = "Emily",
                            Password = "12345",
                            Phone = "444-234-5678",
                            PostalCode = "98765",
                            ProgramId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6451),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Address = "123 Main Road",
                            BirthDay = new DateTime(1990, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anytown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6453),
                            CreatedBy = "Admin",
                            Email = "noah.william@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 3,
                            FirstName = "Noah",
                            FullName = "Noah William Wilson",
                            LastName = "Wilson",
                            MiddleName = "William",
                            Password = "12345",
                            Phone = "123-345-6789",
                            PostalCode = "12345",
                            ProgramId = 3,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6453),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Address = "456 Elm Lane",
                            BirthDay = new DateTime(1991, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6455),
                            CreatedBy = "Admin",
                            Email = "mia.olivia@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 4,
                            FirstName = "Mia",
                            FullName = "Mia Olivia Garcia",
                            LastName = "Garcia",
                            MiddleName = "Olivia",
                            Password = "12345",
                            Phone = "456-567-8901",
                            PostalCode = "54321",
                            ProgramId = 4,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6455),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Address = "555 Oak Road",
                            BirthDay = new DateTime(1989, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6457),
                            CreatedBy = "Admin",
                            Email = "liam.joseph@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 5,
                            FirstName = "Liam",
                            FullName = "Liam Joseph Martinez",
                            LastName = "Martinez",
                            MiddleName = "Joseph",
                            Password = "12345",
                            Phone = "555-234-8901",
                            PostalCode = "98765",
                            ProgramId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6458),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            Address = "666 Pine Lane",
                            BirthDay = new DateTime(1987, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anothercity",
                            Country = "UK",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6460),
                            CreatedBy = "Admin",
                            Email = "isabella.sophia@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 1,
                            FirstName = "Isabella",
                            FullName = "Isabella Sophia Lee",
                            LastName = "Lee",
                            MiddleName = "Sophia",
                            Password = "12345",
                            Phone = "666-345-6789",
                            PostalCode = "98765",
                            ProgramId = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6460),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Address = "123 Main Lane",
                            BirthDay = new DateTime(1992, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anytown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6462),
                            CreatedBy = "Admin",
                            Email = "oliver.james@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 2,
                            FirstName = "Oliver",
                            FullName = "Oliver James Davis",
                            LastName = "Davis",
                            MiddleName = "James",
                            Password = "12345",
                            Phone = "123-567-8901",
                            PostalCode = "12345",
                            ProgramId = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6463),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Address = "777 Elm Road",
                            BirthDay = new DateTime(1993, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Othercity",
                            Country = "Canada",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6466),
                            CreatedBy = "Admin",
                            Email = "sophia.elizabeth@example.com",
                            FacultyId = 3,
                            FieldOfStudyId = 3,
                            FirstName = "Sophia",
                            FullName = "Sophia Elizabeth Brown",
                            LastName = "Brown",
                            MiddleName = "Elizabeth",
                            Password = "12345",
                            Phone = "777-234-5678",
                            PostalCode = "54321",
                            ProgramId = 3,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6466),
                            UpdatedBy = "Admin",
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            Address = "555 Oak Lane",
                            BirthDay = new DateTime(1988, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Sometown",
                            Country = "USA",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6468),
                            CreatedBy = "Admin",
                            Email = "liam.michael@example.com",
                            FacultyId = 1,
                            FieldOfStudyId = 4,
                            FirstName = "Liam",
                            FullName = "Liam Michael Wilson",
                            LastName = "Wilson",
                            MiddleName = "Michael",
                            Password = "12345",
                            Phone = "555-567-9012",
                            PostalCode = "98765",
                            ProgramId = 4,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6468),
                            UpdatedBy = "Admin",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            Address = "666 Maple Road",
                            BirthDay = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Anothercity",
                            Country = "UK",
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6470),
                            CreatedBy = "Admin",
                            Email = "amelia.charlotte@example.com",
                            FacultyId = 2,
                            FieldOfStudyId = 5,
                            FirstName = "Amelia",
                            FullName = "Amelia Charlotte Hernandez",
                            LastName = "Hernandez",
                            MiddleName = "Charlotte",
                            Password = "12345",
                            Phone = "666-234-5678",
                            PostalCode = "98765",
                            ProgramId = 5,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6471),
                            UpdatedBy = "Admin",
                            UserTypeId = 2
                        });
                });

            modelBuilder.Entity("SHB.Domain.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTypeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6253),
                            CreatedBy = "Admin",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6261),
                            UpdatedBy = "Admin",
                            UserTypeCode = "Admin",
                            UserTypeDesc = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6263),
                            CreatedBy = "Admin",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6264),
                            UpdatedBy = "Admin",
                            UserTypeCode = "Teacher",
                            UserTypeDesc = "Teacher"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6265),
                            CreatedBy = "Admin",
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 11, 12, 21, 28, 47, 265, DateTimeKind.Local).AddTicks(6266),
                            UpdatedBy = "Admin",
                            UserTypeCode = "Student",
                            UserTypeDesc = "Student"
                        });
                });

            modelBuilder.Entity("SHB.Domain.Course", b =>
                {
                    b.HasOne("SHB.Domain.Program", "Program")
                        .WithMany("Courses")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("SHB.Domain.FieldOfStudy", b =>
                {
                    b.HasOne("SHB.Domain.Faculty", "Faculty")
                        .WithMany("FieldOfStudies")
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("SHB.Domain.Program", b =>
                {
                    b.HasOne("SHB.Domain.FieldOfStudy", "FieldOfStudy")
                        .WithMany("Programs")
                        .HasForeignKey("FieldOfStudyId");

                    b.Navigation("FieldOfStudy");
                });

            modelBuilder.Entity("SHB.Domain.User", b =>
                {
                    b.HasOne("SHB.Domain.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("SHB.Domain.FieldOfStudy", "FieldOfStudy")
                        .WithMany()
                        .HasForeignKey("FieldOfStudyId");

                    b.HasOne("SHB.Domain.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId");

                    b.HasOne("SHB.Domain.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId");

                    b.Navigation("Faculty");

                    b.Navigation("FieldOfStudy");

                    b.Navigation("Program");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("SHB.Domain.Faculty", b =>
                {
                    b.Navigation("FieldOfStudies");
                });

            modelBuilder.Entity("SHB.Domain.FieldOfStudy", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("SHB.Domain.Program", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
